workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    NeuralSeek:
        inputs:
            - location: ./api.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/neuralseek/sdk/neuralseek
targets:
    neuralseek:
        target: python
        source: NeuralSeek
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/neuralseek/sdk/neuralseek-python-code-samples
            blocking: false
